Add new error types and handle some nonconformant files.
FineFindus/adobe-swatch-exchange-rs pull request #1
Opened 2023-12-20 16:03 UTC by hschimke

New Error Types: Updated errors for certain situations where the Invalid file error was being throw, this clarifies the cause of the error.

Handle some less conformant files: Many files in the wild features group blocks which are not fully parsed together, when this occurs they will incorectly be interpreted as empty. The change fixes this behavior when the group block is not parsed together.

I have attached a zip file containing "in the wild" examples of this behavior.

[DIGITAL COLOR SWATCHES for Adobe.zip](https://github.com/FineFindus/adobe-swatch-exchange-rs/files/13729529/DIGITAL.COLOR.SWATCHES.for.Adobe.zip)

2023-12-20 22:27 UTC, FineFindus requested changes
Thanks for the pr, always nice to see other people find some use in it :)

I would prefer it if the pr could be split into two separate PRs, keeping this one for error handling and creating a new one for parsing non-conforming files. Please also split the commit into several smaller ones, following the guidelines for atomic and [conventional commits](https://www.conventionalcommits.org/).

The new errors look good overall, I've added some review comments about them. Please also add tests for the new errors, checking that malformed input returns the correct error.

> Handle some less conformant files: Many files in the wild features group blocks which are not fully parsed together, when this occurs they will incorectly be interpreted as empty. The change fixes this behavior when the group block is not parsed together.

I'm not sure if I understand exactly what is causing the problem. Do the blocks contain other blocks (I haven't had time to read the attached files yet)?
The new parsing behavior also breaks the current parsing code, e.g. the [read example](https://github.com/FineFindus/adobe-swatch-exchange-rs/blob/master/examples/read.rs) now reads empty groups and colors / the parsing tests fail.
I also think it would be a good idea to add tests for the new parsing to prevent future regressions.

2023-12-20 22:27 UTC, FineFindus commented on src/error.rs
> +        var_name
There is no need to create a variable here, it can be returned immediately

2023-12-20 22:27 UTC, FineFindus commented on src/error.rs
>  }
Please add documentation for these, explaining the error and possibly the correct behavior, e.g. in the case of the file signature, only the file signature `ASEF` is accepted.

2023-12-20 22:27 UTC, FineFindus commented on src/types/mod.rs
> +}
Since this is group specific, it should be moved to `group.rs`.

2023-12-20 22:27 UTC, FineFindus commented on src/lib.rs
> +    let mut group_hld_value = Group::default();
```suggestion
    let mut group_hold = types::GroupHold::Empty;
    let mut group_hold_value = Group::default();
```
Two characters won't kill us, but they make reading easier :)

2023-12-20 22:27 UTC, FineFindus commented on src/error.rs
> +    SliceError,
I'm not sure about this error, it feels a bit too generic, and does not really give the user any clue, about what component failed to get parsed. Will have to think about it a bit more.

2023-12-20 22:27 UTC, FineFindus commented on src/error.rs
> +    /// An erorr occured due to Utf16 parsing issues.
```suggestion
    /// An error occured due to Utf16 parsing issues.
```

2023-12-20 23:35 UTC, hschimke commented
Will do! I'll provide tests and fix the regression. 

I'll split the PRs as well.

2023-12-20 23:56 UTC, hschimke commented
Ah, to address the question of what is happening that I was attempting to fix:

The original code assumes that the group is parsed (Group::parse) with a length that includes the members of the group, but in some files the length of the group block doesn't include the members, only the name of the group. In that case the existing code misses all the members and fails, because it expects to have been able to parse all the members and then find the next block as "group-end". 

An alternate way would be to handle the search for group-end in the Group::parse code, but that involves potentially ignoring the found block length for the group. If I'm refactoring and fixing the regression anyway I might evaluate that method as well.

I may not have done an amazing job explaining what is happening.

2023-12-21 20:11 UTC, hschimke commented
So, it turns out that two things are happening in these files.

1. The files don't have a block length for groups that includes the colors in the group, so the file looks like: BlockStart -> BlockName -> Colors -> BlockEnd. The current implementation looks for BlockStart -> (Block Name + Colors) -> BlockEnd. The difference is basically in how the block length is being encoded for groups. That's pretty easy to solve, and I have a working resolution for it now.
2. The files include a length for GroupEnd blocks. That length is always zero, but it takes up exactly four bytes after each BlockEnd, the current implementation assumes that BlockEnd is immediately followed by the next block. I actually have no idea which way is correct, but I'm having a small amount of trouble figuring out how to account for that difference (mainly since Rust io::Read cannot be rewound, which would be the easy solution). I'm going to keep working on that part.

2023-12-22 08:29 UTC, FineFindus commented
Superseded by #2 and #3.

2023-12-22 08:29 UTC, closed without merging